### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by Junzzzz** [HanghanghangzZ/zookeeperAPI#1]
https://github.com/HanghanghangzZ/zookeeperAPI/blob/c4e94fbcce1a3165450197932595d1a374a92ceb/src/main/java/com/hang/Basic/ZKCreate.java#L85-L93

感觉你应该理解错了，这行指令的功能不是添加帐号一样的意思

```java
// 为当前zookeeper会话添加授权信息
zookeeper.addAuthInfo("digest", "hang:123456".getBytes());
```

简单来说就是登录，相当于后面的请求每次都带上了你的账号密码

**Comment by HanghanghangzZ** [comment]
我试的时候发现如果以这种账号的方式授权创建node节点，在leader中这个账户登陆了，但是在follower中并没有，在follower中并没有权限去操作node节点，而需要我手动的去addauth。
今天我又在Zookeeper的构造方法的注释中发现下面这段注释：


The instantiated ZooKeeper client object will pick an arbitrary server from the connectString and attempt to connect to it. If establishment of the connection fails, another server in the connect string will be tried (the order is non-deterministic, as we random shuffle the list), until a connection is established. The client will continue attempts until the session is explicitly closed.
以及它的翻译
实例化的ZooKeeper客户端对象将从connectString中选择一个任意服务器，然后尝试连接到该服务器。 如果建立连接失败，将尝试使用连接字符串中的另一台服务器（顺序是不确定的，因为我们随机地随机排列列表），直到建立连接为止。 客户端将继续尝试，直到明确关闭会话为止。


然后我在代码中指定了三个ip，我现在猜想是不是因为zookeeper客户端是连接到了leader上，而没有连接到follower上才导致了用户是登录在leader上，而没有登录在follower上。
我使用的zookeeper版本是3.7.0


附：
学长竟然真的有看上传到GitHub上的代码！！！
感谢百忙之中抽出时间观看我的垃圾代码！！！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HanghanghangzZ/zookeeperAPI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月15日(星期四) 晚上7:25
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[HanghanghangzZ/zookeeperAPI] Code Review (#1)





 
https://github.com/HanghanghangzZ/zookeeperAPI/blob/c4e94fbcce1a3165450197932595d1a374a92ceb/src/main/java/com/hang/Basic/ZKCreate.java#L85-L93
 
感觉你应该理解错了，这行指令的功能不是添加帐号一样的意思
 // 为当前zookeeper会话添加授权信息 zookeeper.addAuthInfo("digest", "hang:123456".getBytes());
 
简单来说就是登录，相当于后面的请求每次都带上了你的账号密码

**Comment by Junzzzz** [comment]
emmm... 有点不知道从哪开始讲起

> 在follower中并没有权限去操作node节点，而需要我手动的去addauth

首先连接leader和连接follower会产生两个会话
比喻一下就是你开了两个浏览器，你在leader登了账号，然后创建了节点，并且用了`ZooDefs.Ids.CREATOR_ALL_ACL`，所以授权给了leader里已登录的账号，而这时候follower是没有任何登录信息的，自然没有任何权限

> 我现在猜想是不是因为zookeeper客户端是连接到了leader上

此外zookeeper的一个机制就是写操作都会在leader上进行，然后同步给follower，如果你在follower上做写入之类的操作，follower会转发给leader

> The instantiated ZooKeeper client object will pick an arbitrary server from the connectString and attempt to connect to it. If establishment of the connection fails, another server in the connect string will be tried (the order is non-deterministic, as we random shuffle the list), until a connection is established. The client will continue attempts until the session is explicitly closed.

这段话的意思应该是找到一台可用的服务器并且建立连接，无论连leader或者是follower其实都是无所谓的

**Comment by HanghanghangzZ** [comment]
> zookeeper的一个机制就是写操作都会在leader上进行，然后同步给follower，如果你在follower上做写入之类的操作，follower会转发给leader

原来是这样，之前问一个学长，zookeeper的leader和follower有没有区别，他说没有区别。。。(⊙﹏⊙)


学长，我还有几个问题
1.在分布式环境中，有些业务逻辑只需要集群中的某一台机器进行执行， 其他的机器可以共享这个结果，这样可以大大减少重复计算，提高性能，所以就需要主节点。那么在zookeeper集群的实际应用中，是否也是像redis集群一样是读写分离的呢？读请求由follower完成，而写请求由leader完成，只是写请求是可以被发送给任意一个节点。

2.如果我连接到的是follower。我的登录用户的命令，会被follower转发给leader咯？

**Comment by Junzzzz** [comment]
leader和follower在抽象后确实是一样的，因为每个follower都可以是leader（宕机后会重新选举），设计者在设计调用接口的时候就是让使用者无需去关注是否为leader。

看了两个问题，感觉还是在概念的理解上还是有偏差

> 这样可以大大减少重复计算，提高性能

所谓的分布式并不是减少重复计算，而是由于机器性能达到瓶颈，无限提升一台机器的性能是不可能的，同时经济效益也不高
相当于1个人搬10个箱子，现在我开10台机器，10个人搬10个箱子，这里会有个中间商（网关）去分配这些任务，让请求尽可能均衡的分配到每个人身上

> 那么在zookeeper集群的实际应用中，是否也是像redis集群一样是读写分离的呢

严格的讲，不是，zookeeper的写操作是由leader排好序分发给每个follower去执行的，而redis保证数据一致性是通过复制（数据打包成文件发送）。其实redis和zookeeper在功能上很类似，但是zookeeper更偏向一个监控器，而redis更偏向数据库
具体的还是慢慢去使用学习吧，一句两句讲不清

> 如果我连接到的是follower。我的登录用户的命令，会被follower转发给leader咯？

`addAuthInfo`其实并不是理解的传统的登录，他相当于是把你的每个请求上都带了账号密码
因为你的账号密码已经写入节点信息里了，follower直接比较节点里的账号密码信息和你每次请求带的是不是一样就ok，不需要转发

**Comment by HanghanghangzZ** [comment]
我懂了！！感谢Jun哥！你理解的好深刻(❤ε❤)
